### ISSUE TITLE
How to return custom exception instead of CaughtException.

### ISSUE THREAD

**Issue by xsahil03x** [boyan01/resultk.dart#3]
I am returning some custom exceptions from one of my function.

`   items.onFailure((e) {
      showError(e);
    });
`
My showError takes my custom exception as an input.

`  showError(ApiException error) => _subjectBaseError.sink.add(error);
`

I tried casting it to ApiException but it didn't work. 
`Unhandled Exception: type 'CaughtException' is not a subtype of type 'ApiException'`

**Comment by boyan01** [comment]
https://github.com/boyan01/resultk.dart/blob/7fa208bc5cf5dc6b5bd295101af9155444f20f8b/lib/resultk.dart#L225

`CaughtException.exception` is the real exception which throwed by `throw` statement.

---

The reason we used CaughtException to wrap the original exception is because we need to receive the `stacktrace` information.

**Comment by xsahil03x** [comment]
Yes got your point, Thanks.

**Comment by xsahil03x** [comment]
Hey @boyan01, should we also include this helper function in Readme for leveraging the best out this package ?

```dart
import 'package:resultk/resultk.dart';

typedef AsyncCallback<T> = Future<Result<T>> Function();

Future<Result<T>> safeApiCall<T>(
    AsyncCallback<T> call, String errorMessage) async {
  try {
    return await call();
  } on Exception catch (e) {
    // An exception was thrown when calling the API
    // so we're returning a failure
    return Result.failure(e);
  }
}
```

**We can use it like this ->**

```dart
  @override
  Future<Result<List<OnBoardingItem>>> fetchItemList() async {
    return safeApiCall<List<OnBoardingItem>>(
      () => _requestItemList(),
      'Unable to fetch Restaurant Items',
    );
  }
```

**Comment by boyan01** [comment]
It looks a bit similar to this method

https://github.com/boyan01/resultk.dart/blob/7fa208bc5cf5dc6b5bd295101af9155444f20f8b/lib/resultk.dart#L203

**Comment by xsahil03x** [comment]
Yes didn't check it. Awesome :+1:
